"""empty message

Revision ID: 26bf36a9c2fd
Revises: 08e8c2c334a7
Create Date: 2025-10-19 21:44:58.170103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26bf36a9c2fd'
down_revision: Union[str, Sequence[str], None] = '08e8c2c334a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidate', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'user_id')
    # ### end Alembic commands ###
