"""fix file path

Revision ID: 821f48e875c9
Revises: da3e59ede120
Create Date: 2025-10-24 06:04:04.166965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '821f48e875c9'
down_revision: Union[str, Sequence[str], None] = 'da3e59ede120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('cv_paths', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('candidate', sa.Column('project_report_paths', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('candidate', sa.Column('evaluation_result_json', sa.JSON(), nullable=True))
    op.add_column('candidate', sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('candidate', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('candidate', 'error')
    op.drop_column('candidate', 'evaluation_result_json')
    op.drop_column('candidate', 'project_report_paths')
    op.drop_column('candidate', 'cv_paths')
    # ### end Alembic commands ###
